virtool/virtool-core

virtool_core/models/user.py

Move several fields to the full model. The minimal model was too big.
BREAKING CHANGE: This remove fields from the minimal user representation.

fix: reduce minimal user model

---

virtool_core/models/group.py
virtool_core/models/user.py

I am adding this because the `Group` model with the `permissions` field is excessive for nesting in `User` models. This minimal model does not have the `permissions` field.

fix: add an id-only minimal group model

---

virtool_core/models/user.py

Users don't need to have primary groups assigned (`None`).

fix: make the user.primary_group field optional

---

virtool_core/models/samples.py

This should be only in complete sample representations. Move it into `Sample` from `SampleMinimal`.

fix: remove subtraction field from SampleMinimal

---

virtool_core/models/job.py

Jobs don't have a stage when they are in the waiting and preparing states.

fix: make job stage nullable

---

virtool_core/models/samples.py

Workflow tags with workflows still in-progress have the value `"ip"`.
This is a stupid design and should be changed to an enum value (eg. `none`, `pending`, `ready`).

fix: allow strings for sample workflow tag fields

---

virtool_core/models/hmm.py

This field should never be sent in responses. It is a flag indicating that the HMM is invisible to users.

fix: remove hmm hidden field

---

virtool_core/models/upload.py

Used BaseModel instead of SearchResult since pagination is not used in uploads.

feat: add model for upload search result

---

virtool_core/models/subtraction.py

This value isn't set until after the creation workflow finishes.

fix: make substraction count optional

---

virtool_core/models/subtraction.py

For older subtractions, user information was not retained.

fix: make subtraction user field optional

---

virtool_core/models/otu.py

* Make `remote` optional for OTUs and sequences.
* Make `segment ` optional.
* Make `issues` optional.
* Make `last_indexed_version` optional.

fix: correct otu models

---

virtool_core/models/__init__.py
virtool_core/models/analysis.py
virtool_core/models/group.py
virtool_core/models/history.py
virtool_core/models/index.py
virtool_core/models/project.py
virtool_core/models/reference.py
virtool_core/models/upload.py

`UserMinimal` is too detailed to be nested in most models. This PR replaces uses of `UserMinimal` with `UserNested` in many places.

fix: use nested users in most places

---

virtool_core/models/reference.py

Add a ReferenceSearchResult model as a return type for `get` in references/api

feat: add reference search model

---

virtool_core/models/index.py
virtool_core/models/reference.py

Index models:
Added change_count to IndexSearchResult and moved ready to IndexMinimal.
Reference models:
Added created_at to ReferenceGroup which was missed in the last PR. Also added imported_from to ReferenceMinimal and
targets to Reference in case the data_type is "barcode"
Did not change data_type and organism to be Optional as I believe those fields being None is a bug.

feat: update reference and index models

---

virtool_core/models/task.py

When tasks have not been started, their step may be `None`.

fix: make task step field optional

---

virtool_core/models/blast.py

Did not inherit from BaseModel in previous commit.

fix: use pydantic for blast model

---

virtool_core/models/session.py

Proposed new model for sessions in virtool. 
Varies mildly from current session dictionary in use in that many fields that it uses the `NestedUser` model for the user field. In an effort to reduce redundancy the administrator field is no longer explicitly defined as it is contained with the definition of `NestedUser`.  Possible downside is that it may again be required to define administrator explicitly again should the definition of a `NestedUser` be changed to no longer include the administrator field. 
Alternative approach: Alternatively we could instead define user as an instance of the `User` model which would result in implicit inclusion of most of the variables currently defined in the session object. This approach was not taken due to the inclusion of additional data superfluous …

feat: add session model

---

virtool_core/models/otu.py

BREAKING CHANGE: Replace usages of OTUSequence with Sequence. OTUSequence is meant to be nested in OTUs.

fix: remove reference field from `OTUSequence`

---

virtool_core/models/user.py

Need a model for returning a paginated list of users from the administrators view.`UserSearchResult` is not currently in use in the codebase. Could add `UserMinimalSearchResult` for the case of getting a list of basic `UserMinimal` objects for display, but we are more likely to want `UserNestedSearchResult` imo

fix: include full user in UserSearchResult

---

virtool_core/models/group.py

Groups created only in Postgres will not have legacy IDs.

fix: make `Group.legacy_id` optional

---

virtool_core/models/analysis.py
virtool_core/models/ml.py

BREAKING CHANGE: Analyses without `ml` fields will fail validation.

feat: add analysis `ml` field

---

virtool_core/models/user.py

* Use `administrator_role` instead.
BREAKING CHANGE: The `administrator` field no longer exists.

fix: drop `User.administrator` field

---

virtool_core/models/account.py
virtool_core/models/reference.py

BREAKING CHANGE: Breaks functionality relying on `administrator` flags.

fix: remove all `administrator` fields

---

pyproject.toml

This actually just updates the contributors. A previous commit adds support for 3.11 and 3.12.

fix: support python 3.10 - 3.12
