virtool/virtool-core

.drone.yml
README.md

Calculate test coverage during CI run and report to Codacy. Add Drone build badge to readme.

Test coverage reporting

---

.github/workflows/ci.yml
.github/workflows/publish.yml
poetry.lock
pyproject.toml
tests/caches/snapshots/snap_test_db.py
tests/caches/test_db.py
tests/db/test_core.py
tests/history/test_db.py
tests/history/test_utils.py
tests/otus/test_utils.py
tests/test_bio.py
tests/test_utils.py
virtool_core/bio.py
virtool_core/caches/db.py
virtool_core/caches/utils.py
virtool_core/history/db.py
virtool_core/history/utils.py
virtool_core/samples/utils.py
virtool_core/subtractions/utils.py
virtool_core/utils.py

This matches `virtool` and `virtool-core`.
Also, rename the GitHub actions files and pin `ubuntu-20.04`.

Change string paths to Path

---

docs/reference.rst
virtool_core/data_model/__init__.py
virtool_core/data_model/analysis.py
virtool_core/data_model/files.py
virtool_core/data_model/hmms.py
virtool_core/data_model/indexes.py
virtool_core/data_model/jobs.py
virtool_core/data_model/otus.py
virtool_core/data_model/references.py
virtool_core/data_model/samples.py
virtool_core/data_model/subtractions.py

Add classes from `virtool_workflow.data_model` package.
The doc-strings have been updated to include parameter descriptions in the class doc-string.

Add data-model classes.

---

poetry.lock
pyproject.toml
tests/conftest.py
tests/models/json/analysis.json
tests/models/test_analysis_model.py
virtool_core/models/__init__.py
virtool_core/models/analysis.py

Add a `pydantic` data model for the Analysis record.
Maps 1-1 with the [docs](https://release-5-0-0.virtool.ca/docs/developer/backend/model/).

Introduce Pydantic Model for Analysis

---

poetry.lock

fix: resolve aiohttp security issue

---

tests/models/test_analysis_model.py
virtool_core/models/__init__.py
virtool_core/models/label.py
virtool_core/models/project.py

* Add project models.
* Generalize hex color validator.
* Remove package level exports.

feat: add provisional project models

---

virtool_core/models/subtraction.py

* Make some fields optional. These are not populated until the creation workflow completes.
* Remove usages of `Field` and unwanted default values.

fix: update subtraction models

---

virtool_core/models/searchresult.py

Looked into many workarounds for the first option but they all failed. We will have to go for the second option and build each model on top of SearchResult.

feat: add search result model

---

virtool_core/models/samples.py

This field is not populated until samples are finalized.

fix: make sample quality nullable

---

virtool_core/models/job.py

* Use `UserNested`.
* Move some fields out of `UserMinimal`.
* Make `args` a generic dict instead of a model.

fix: make job model more accurate

---

virtool_core/models/subtraction.py

* Remove `subtraction.deleted`. This is not a public field.
* Remove `subtraction.has_file`. This is not a public field.
* Use `UserNested` in subtraction models. 
* Remove bad optional and default values.
* Accept str and int for subtraction upload id
* Only accept `SubtractionUpload` for the `file` field.

fix: update subtraction model

---

tests/models/test_otu.py
virtool_core/models/enums.py
virtool_core/models/otu.py

* Add `Molecule` enum.
* Make `molecule` optional.
* Fix `OTU.schema` shadowing a `BaseModel` attribute.

fix: accept optional enum for segment molecule

---

virtool_core/models/history.py
virtool_core/models/otu.py

* Add a nested history model (`HistoryNested`) for use in OTU models.
* Use the nested model in the OTU model.

Nested history

---

virtool_core/models/otu.py

OTUs don't actually have a user field.

fix: remove otu user field

---

virtool_core/models/reference.py
virtool_core/models/task.py

Created TaskNested which is used in the Reference model.
Also allow None values for certain fields in the Reference model.

feat: update reference and task models

---

virtool_core/models/reference.py

* Remove users and groups from minimal.
* Make some fields optional.

fix: correct reference models

---

.github/CODEOWNERS

* Add @ReeceHoffmann to codeowners.
* Remove @BlakeASmith from codeowners.

docs: update codeowners

---

virtool_core/models/otu.py

* Add `target` field to models.
* Remove duplicate field definitions.

fix: add `target` field to sequence models

---

virtool_core/models/administrator.py
virtool_core/models/user.py

Total change of path, now just adding `role` as an optional field for `User`.

Add role field to user model

---

virtool_core/models/index.py

replaced type JobNested with JobMinimal in the IndexMinimal model

feat: replace JobNested with JobMinimal

---

virtool_core/models/ml.py

BREAKING CHANGE: Some fields have been removed in `analysis.ml.model`.

fix: include fewer fields in nested ml models

---

.readthedocs.yaml
docs/Makefile
docs/conf.py
poetry.lock
pyproject.toml
virtool_core/logging.py
virtool_core/redis.py

- Configured `docs/conf.py` for building sphinx docs
- Added Intersphinx mapping for linking object references across `virtool-workflow`, `dev`, `virtool`
- Added `piccolo_theme` to docs 
- Added `readthedocs.yaml` config

Bryce davidson/vir 1990 get virtool core building on readthedocs

---

docs/conf.py

- Updated the intersphinx mapping object to reflect production URLs

docs: update intersphinx mapping for production URLs

---

tests/test_bio.py
tests/test_redis.py
virtool_core/bio.py
virtool_core/redis.py

* Add `connect` and `close` methods. They are used by the context manager.

feat: allow redis connection outside context manager

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml

BREAKING CHANGE: Breaks compatibility for workflows using other Python versions.

feat: only support python-3.12

---

tests/models/test_otu.py
virtool_core/models/otu.py

**Changes:**
- When host is `None` converts it to instead return an empty string

Allow none for host field of OTUSequence
